import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:http/http.dart' as http;

class PopUpController extends GetxController {
  var checkboxValues = <bool>[false, false, false].obs;
  List<String> selectedTests = [];
  var isNextButtonEnabled = false.obs;
  final RxBool isLoading = false.obs;

  final TextEditingController emailCntrl = TextEditingController();
  final TextEditingController username = TextEditingController();
  final TextEditingController mobnoCtrl = TextEditingController();

  List<String> labtestdata = [
    "CBC",
    "Glyco Hemoglobin",
    "Glucose - Fasting",
    "Creatinine",
    "Thyroid Function Test",
    "Urine Examination",
    "Lipid Profile",
    "Glucose - Post Prandial",
    "TSH",
    "Urea",
    "ESR",
    "Liver Function Test",
    "Free TFT",
    "Glucose - Random",
    "Electrolytes",
    "Haemoglobin",
    "25 OH Cholecalciferol (D2+D3)",
    "Culture,Aerobic, Urine",
    "Blood Group & RH",
    "Calcium",
    "Kidney Function Test",
    "Uric Acid",
    "Vitamin B - 12 Level",
    "HBs antigen",
    "Peripheral Smear",
    "Blood Urea Nitrogen (BUN)",
    "C- Reactive Protein",
    "ECG - Mumbai",
    "Free Thyroxine(Free T4)",
    "HIV I & II",
    "Sensitivity Panel(Manual-1)",
    "Prolactin level",
    "Beta HCG level",
    "Prothrombin Time (Photooptical clot detection)",
    "Rapid Plasma Reagin (VDRL)",
    "HCV antibody Total",
    "Estradiol level",
    "Leutinizing Hormone level",
    "Audiometry Test",
    "Progesterone level",
    "SGPT (ALT)",
    "Biopsy - Small Specimen BP10",
    "Physician Examination",
    "SPIROMETRY",
    "Urine Examination -U ( Flow Cytometry )",
    "Prostate Specific Antigen level",
    "Follicle Stimulating Hormone level",
    "IgE level",
    "Bilirubin level Total",
    "NDPL T20 Package",
    "Rheumatoid Factor",
    "Ferritin",
    "Anti Mullerian Hormone",
    "VISIT 100",
    "Cholesterol",
    "SGOT (AST)",
    "Lipase",
    "Phosphorus Inorganic",
    "Amylase-Serum",
    "Microalbumin Level from urine",
    "Haemogram with ESR (CBC-ESR)",
    "Blood Culture 1 set",
    "Anti Nuclear Antibody ( IIF )",
    "Potassium",
    "Activated Partial Thromboplastin Time (Photooptical clot detection)",
    "USG abdomen",
    "HIV MANUAL",
    "Manual Hbs Ag Hepacard",
    "Absolute Eosinophil Count",
    "C.A.-125 level",
    "High Sensitive CRP",
    "Double Marker",
    "Bactec Aerobic Culture",
    "KIDNEY PANEL - 1",
    "Glucose,Post Prandial - 1hr 30mts,Plasma",
    "Bleeding Time ( Ivy's method )",
    "Clotting Time",
    "Sodium",
    "TOTAL WBC COUNT",
    "Iron Level",
    "Folic Acid level",
    "Differential Count",
    "EYE Test (Near,Far and Color)",
    "Pyogenic Culture And Sensitivity For Bacteria",
    "Dengue Antigen NS1 Elisa",
    "Haemogram (CBC)",
    "Iron Studies (TIBC)",
    "Stool Examination",
    "Liquid Base Cytology PAP",
    "WIDAL by tube method",
    "Antistreptolysin - O",
    "Estimated Glomerular Filtration Rate (eGFR)",
    "Carcino Embryonic Antigen level",
    "HCV antibody-Rapid",
    "Testosterone level",
    "IRON PROFILE CBCC",
    "Anti CCP Level",
    "Dengue antibody IgM",
    "Free Triiodothyronine(Free T3)",
    "Bleeding Time & Clotting Time",
    "FreeT4 & TSH",
    "Dengue Profile Rapid",
    "VISIT 300",
    "HB Electrophoresis (HPLC)",
    "Alpha Feto Protein level",
    "Flu a, Flu B and H1N1 Qualitative by Real-time PCR",
    "Thyroperoxidase Antibody (Anti-TPO)",
    "Homocysteine level",
    "Mycobacterium Tuberculosis DNA PCR (GeneXpert)",
    "Malarial parasites by QBC",
    "Urine Glucose (Post Prandial)",
    "Insulin Fasting",
    "Absolute Neutrophil Count",
    "Absolute Monocyte Count",
    "Absolute Basophil Count",
    "Magnesium Level",
    "Platelet Count",
    "Triglyceride",
    "SARS-CoV-2 IgG",
    "CA-19-9 level",
    "CBCESR",
    "Urine Glucose (Fasting)",
    "DDimer",
    "Rubella antibody IgG",
    "Biopsy Medium",
    "AFB (ZN) stain for Sputum",
    "Papsmear (Conventional)",
    "ANA PROFILE (Auto antibody profile)",
    "LDH",
    "Tread Mill Test",
    "Cortisol 8 AM",
    "HCV (Hepatitis C) Qualitative by Real-time PCR",
    "Alkaline Phosphatase level",
    "Para Thyroid Hormone Intact level",
    "Scrub Typhus antibody IgM",
    "Lipoprotein (a)",
    "Urinary Protein Creatinine Ratio",
    "Cardiolipin antibody IgM",
    "Cardiolipin antibody  IgG",
    "HBs antibody",
    "PCV",
    "Neu Pro Check",
    "Semen Analysis",
    "Dengue antibody IgG",
    "NT- proB - Type Natriuretic Peptide level",
    "ARTERIAL BLOOD GAS (ABG)",
    "Thyroxine",
    "Quantiferon TB Gold (IGRA)",
    "GTT 3 Sample",
    "Protein Electrophoresis ( Capillary )",
    "Rapid Plasma Reagin (VDRL)",
    "Culture,Aerobic, Sputum",
    "FSH,LH,Prolactin",
    "CPK Total",
    "Complement  3  Level",
    "LUPUS ANTICOAGULANT (AS PER ISTH-2009)",
    "Leptospira antibody IgM",
    "Complement 4 Level",
    "Thyroglobulin antibody",
    "Biopsy - Large Specimen BP20",
    "Apolipoprotein A-1+B",
    "Anti Neutrophilic Cytoplasmic Antibodies ( IIF )",
    "OT Microbiological Surveillance 1 Swab",
    "THYROID PROFILE EXTENDED",
    "Coombs Test Indirect (By Gel Technology)",
    "TOTAL PROTEIN",
    "Anti ds DNA ( IIF )",
    "Urinary Protein Creatinine Ratio",
    "Beta 2 Glycoprotein 1 antibody IgM",
    "Pregnancy Test - Urine",
    "Ammonia",
    "Beta 2 Glycoprotein 1 antibody IgG",
    "IgG level",
    "Procalcitonin",
    "Triiodothyronine",
    "Urine Ketone",
    "Free Testosterone",
    "Reticulocyte Count  ( Automated )",
    "HBV (Hepatitis B) Quantitative by Real-time PCR",
    "C-Peptide,Fasting,Serum",
    "TPHA",
    "Urinary Protein",
    "HAV antibody IgM",
    "Phospholipid antibody IgM",
    "DHEA-S",
    "Free PSA/PSA Ratio",
    "EYE TEST(Near,Far,Color and incl. refraction)",
    "Coombs Test Direct (By Gel Technology)",
    "Phospholipid antibody IgG",
    "Anti Nuclear Antibody by ELISA, Serum",
    "Bactec Aerobic Culture",
    "HIV-1 (Human Immunodeficiency Virus-1) Quantitative by Real-time PCR",
    "Blood Pressure",
    "Fecal Calprotectin Level ",
    "New Born Screening-G6PD",
    "MPO antibody (P-ANCA)",
    "LDL Cholesterol (Direct)",
    "PR3 antibody (C-ANCA)",
    "HLAb 27 By Flowcytometry",
    "Gram stain",
    "Fibrinogen Level ( Clauss Method )",
    "Glucose,Post Prandial - 2hrs (After 75 gms GLU)",
    "Bactec Anaerobic culture",
    "Troponin I",
    "ORION (WES-Whole Exome Sequencing)",
    "Karyotyping From Blood",
    "Insulin 2 Hrs After Glucose/Lunch",
    "Cytology",
    "HBc Total antibody",
    "AFB stain",
    "Gamma Glutamyl Transferase (GGT)",
    "Glucose 1hr",
    "Adenosine Deaminase From Body Fluids",
    "Albumin-Serum",
    "Body Mass Index",
    "Rubella antibody IgM",
    "CD4/CD8 ABSOLUTE COUNTS- (CD 3/4/8/45 BY FLOWCYTOMETRY)",
    "Lipid profile, Comprehensive",
    "HEV IGM MANUAL",
    "Tacrolimus Level (TDM)",
    "Allergy- Aspergillus specific IgE",
    "HBe Antigen",
    "Quadruple Marker",
    "HSV (Type II) antibody IgM",
    "Angiotensin Converting Enzyme Level",
    "Glucose Challenge Test",
    "Urine Glucose (Random)",
    "Biopsy Extra Large",
    "NEWBORN SCREENING TEST SUMMARY REPORT",
    "Mantoux Test",
    "HSV (Type II) antibody IgG",
    "HSV Type I antibody IgM",
    "Human papiloma virus (HPV) detection by Real Time PCR",
    "HDL Cholesterol",
    "HSV Type I antibody IgG",
    "C.M.V antibody IgG",
    "Troponin T",
    "S.Typhi antibody IgM",
    "CPK-MB level",
    "VACCINATION (TYPHOID)",
    "Sensitivity Panel(Manual-1)",
    "Total Iron Binding Capacity(TIBC) ,Serum",
    "Glucose - Post Prandial",
    "Digital Retinal screening",
    "C.M.V. antibody IgM",
    "Transferrin Level",
    "G6PD",
    "FNAC procedure",
    "Stone Analysis ( FT-IR )",
    "Anti Thyroid Antibody",
    "Ceruloplasmin level",
    "Osmolality Urine",
    "Apolipoprotein B",
    "Varicella Zoster antibody IgG",
    "Occult Blood",
    "Chloride",
    "Fungus Culture",
    "Manual Hbs Ag Hepacard",
    "Acetyl Choline Receptor Binding Antibody",
    "Malarial parasite (  smear )",
    "HCV (Hepatitis C) Quantitative by Real-time PCR",
    "Bile Acid",
    "Ionic Calcium",
    "X-RAY SPINE AP OR LATERAL",
    "Osmolality Serum",
    "Chlamydia Trachomatis antibody IgG",
    "Adenosine Deaminase From Blood",
    "TORCH IgM",
    "Urinary Protein-24 hours",
    "IgA level",
    "IL-6 level",
    "ACTH Level [Adrenocorticotropic hormone]",
    "17-Hydroxy Progesterone level",
    "Apolipoprotein A - 1",
    "Lithium level (TDM)",
    "Leptospira antibody IgG",
    "C-Peptide,PP,Serum",
    "Thyroglobulin level",
    "HIV-1 (Human Immunodeficiency Virus-1) Qualitative by Real-time PCR",
    "HBc antibody  IgM",
    "Triple Marker",
    "Absolute Lymphocyte Count",
    "PROTEIN S, FUNCTIONAL #",
    "Protein C Assay ( Chromogenic )",
    "Torch IgG",
    "Chlamydia Trachomatis antibody IgM",
    "Allergy- Aspergillus specific IgE",
    "S.Typhi antibody IgG & IgM",
    "Cystatin C",
    "KOH Preparation",
    "Syphilis Antibody",
    "X-RAY Cervical Spine - AP/Lat. View",
    "Biopsy Large",
    "Zinc Level",
    "Estimated Glomerular Filtration Rate (eGFR)",
    "OT MICROBIOLOGICAL SURVEILLANCE (ANAEROBIC )",
    "TMT OR ECHO",
    "Bactec Aerobic Culture",
    "Malaria ( PF/PV) antigen test",
    "LDH, Body Fluids",
    "Bactec Aerobic Culture",
    "IgG4Subclass",
    "Cell Count,Body fluid",
    "Rh Antibody titre",
    "Aspergillus Antigen (Galactomannan)",
    "Anti Smooth Muscle Antibody ( IIF )",
    "Valproic acid (TDM)",
    "Lactate Level",
    "Aspergillosis antibody IgG",
    "Anti Thrombin  III",
    "Urinary Sodium -Spot",
    "PHENOL, Urine",
    "IgM level",
    "Lead Level",
    "Free Prostate Specific Antigen",
    "Copper Level ",
    "Troponin I Manual",
    "Cortisol PM",
    "X-Ray Chest AP",
    "LKM1 antibody-ELISA",
    "USG Breast",
    "Bence Jones Protein",
    "Non-Invasive Prenatal Testing (NIPT)#",
    "HAV IGM MANUAL",
    "TSH Receptor Antibody",
    "Measles Antibody IgG",
    "CA-15-3 level",
    "Mycobacterium Tuberculosis (MTB) Qualitative by Real-time PCR",
    "GAD Antibody",
    "Cell Count,CSF",
    "Human Growth Hormone level",
    "Immunoelectrophoresis with IG profile",
    "HBe antibody",
    "D3-Hydroxybutyrate (Ketone body), Serum",
    "OT Microbiological Surveillance- Biological indicator",
    "Karyotyping From Bonemarrow ",
    "B - 2 Microglobulin level - serum",
    "New Born Screening-Phenylalanine",
    "FACTOR V (Leiden) G1691A by Real-time PCR",
    "Mumps antibody IgG",
    "Covid Spike Protein IgG",
    "Haptoglobin level",
    "Fluid analysis - Body Fluid",
    "ASCA IgA",
    "HSV II Profile",
    "IMMUNOHISTOCHEMISTRY 1 Marker#",
    "ASCA IgG #",
    "Focus Non Invasive Prenatal Testing (NIPT-FOCUS)",
    "Inhibin B Level",
    "HLA B 27 By Real-time PCR",
    "AFB Culture (MGIT)",
    "OT Microbiological Surveillance 10 Swabs",
    "CSF Electrophoresis-Oligoclonal band",
    "Microbiological examination",
    "Encephalitis Panel ( Cell based study )",
    "ORION Focus (Clinical Exome/Mendeliome/Panel testing)",
    "EBV VCA antibody IgM",
    "Dilantin (Phenytoin) level (TDM)",
    "Antiphospholipid Antibody Panel",
    "Insulin like Growth Factor - 1 level",
    "Erythropoetin level",
    "Biochemical examination,CSF",
    "Tissue Transglutaminase antibody IgA (TTG-A)",
    "Microalbumin creatinine ratio, Urine",
    "Dihydrotestosterone level",
    "Activated Partial Thromboplastin Time (Photooptical clot detection)",
    "Fructosamine",
    "MCC Check by QF-PCR",
    "Chromogranin-A level",
    "HSV1/2 IgG",
    "Vitamin D - 1,25 Dihydroxy",
    "Smear for Microfilaria",
    "Glomerulo Basement Membrane antibody",
    "Immunohistochemistry, any 4 markers#",
    "Anti MuSK Antibodies ",
    "Urine Myoglobin",
    "HSV1/2 IgM",
    "VACCINATION-HEPATITIS B",
    "HBV (Hepatitis B) Qualitative by Real-time PCR",
    "Phospholipase A2 Receptor Antibody IgG (PLA2R)",
    "Urine Multiplex PCR for STDs",
    "HIV Western Blot",
    "Chikungunya antibody IgM",
    "H.Pylori antibody IgG",
    "NMO ( Cell based study )",
    "Cytology",
    "PYRUVATE, PYRUVIC ACID#",
    "GLUCOSE, BODY FLUID",
    "BUN/Creatinine Ratio",
    "Urinary Copper-24 hours",
    "FOLATE (FOLIC ACID), RBC",
    "Anti Aquaporin 4 (NMO) and Myelin Oligodendrocyte glycoprotein (MOG) antibody",
    "Homa IR (Mass Unit)",
    "Insulin Random",
    "Glucose Tolerance Test(Gestational) 3hrs,4 samples",
    "EBV EBNA antibody IgG",
    "Myelin Oligodendrocyte Glycoprotein(MOG) Antibody#",
    "Urinary Creatinine-24 hours",
    "Bicarbonate",
    "CMV (Cytomegalovirus) Quantitative BY Real-time PCR",
    "Mitochondrial Part of ORION",
    "Sex Hormone Binding Globulin level",
    "Fibrinogen Degradation Product ( Latex )",
    "OT Microbiological Surveillance 3 Swabs",
    "VISIT 300",
    "Protein With A/G Ratio",
    "Aldosterone level",
    "X-RAY Both Knee Joint - AP/Lat. View",
    "USG PELVIS",
    "OT Microbiological Surveillance 5 Swabs",
    "Clostridium Difficile GDH Ag + Toxin A and B Detection From Stool",
    "HLA-B*15:02",
    "Immunofixationprofile",
    "Chlamydia and Gonorrhea Profile",
    "H.Pylori Antigen Detection from stool",
    "OT Microbiological Surveillance 4 Swabs",
    "Toxo antibody IgG",
    "Heavy Metal Analysis from blood",
    "Anti Parietal Cell Antibody ( IIF )",
    "Microarray Rapidsure, Deepdive (750k)",
    "Urinary Potassium -Spot",
    "Cortisol level- Random",
    "X-RAY SHOULDER AP/ LAT",
    "Free Kappa Lambada Chain Ratio",
    "Sperm antibody",
    "Bone Marrow Aspiration",
    "DHEA,Serum",
    "Protein Fluid",
    "Fecal Elastase-1",
    "CYP2C19 Genotyping for Clopidogrel Resistance Assay",
    "HCV antibody IgM",
    "Activated Protein C Resistance #",
    "Microfilaria by QBC",
    "USG KUB HD",
    "1,3-Beta D Glucan Level",
    "Toxo antibody IgM",
    "Inhibin A Level",
    "Biochemical examination,Body fluid",
    "Frozen Section 5",
    "HLA typing A,B,C,DQB1,DRB1,DPB1",
    "H.Pylori antibody IgA",
    "Immature Platelet Fraction",
    "Fluid Albumin",
    "Histopathology Slide",
    "Hbs Ag Quantitative",
    "Anti Mitochondrial Antibody ( IIF )",
    "BCR-ABL Quantitative - SNG",
    "JAK2 V617F Mutation Study by Real-time PCR (V617F)",
    "Metanephrine level-Plasma",
    "Covid 19-Antibody Panel (Total, G, M)",
    "Glucose,Post Prandial - 1hr (After 75 gms GLU)",
    "Renin Activity",
    "Urinary Creatinine-Spot",
    "EBV (NA) IgM antibody #",
    "Free Androgen Index (FAI)",
    "H.Pylori antibody IgM",
    "Urinary Metanephrine -24 hours",
    "X-RAY FOOT AP / OBLIQUE",
    "Prenatal Microarray 750K",
    "Methhaemoglobin, Blood#",
    "Protein Fluid",
    "C1 Esterase Inhibitor",
    "HSV I&II (Herpes Simplex Virus I&II) Qualitative by Real-time PCR",
    "LIVER AUTO ANTIBODY PROFILE#",
    "ORION (WES-Whole Exome Sequencing)",
    "Brucella antibody IgM",
    "Cryoglobulin Estimation",
    "Gastrin Level",
    "EBV VCA antibody IgG",
    "Immunohistochemistry, any 3 markers#",
    "RBC",
    "Anti ds DNA antibody, EIA",
    "S.Typhi antibody IgG",
    "Cortisol -Basal,Serum",
    "Widal by Slide Method",
    "USG Thyroid",
    "Measles Antibody IgM",
    "CD19 and CD19 Abs count(IPT)",
    "HLA -Typing For  Class I And Class II (HLA A, B, C, DR & DQ) HIGH RESOLUTION#",
    "Sickling Test ( Dithionate )",
    "Myositis Profile - 16",
    "Hepatitis E Virus antibody IgG",
    "NEURONAL (PARANEOPLASTIC) AUTOANTIBODIES PROFILE#",
    "OT Microbiological Surveillance 6 Swabs",
    "Vitamin C",
    "OT Microbiological Surveillance 7 Swabs",
    "Tumor Necrosis Factor (TNF) Alpha level",
    "Cyclosporine Level (TDM)",
    "IHC Marker PDL1 ",
    "Chimerism Study",
    "Vitamin B6",
    "GTT Extended (5 samples)",
    "Onco haem (DNA+RNA) (AML and B-ALL By NGS) ",
    "Trephine biopsy for histopathological examination.",
    "DSA by Luminex (HLA Cross Match)",
    "Neisseria Gonorrhoeae Qualitative by Real-time PCR",
    "Calcitonin level",
    "Carbamezapine level (TDM)",
    "Soluble Liver Antigen",
    "Homocysteine, Urine#",
    "Protein CSF",
    "Alpha 1 Antitrypsin",
    "Beta 2 Glycoprotein-1 (IgA) #",
    "SS-A/Ro antibody",
    "CSF HSV I antibody IgM",
    "Sanger Testing For 1 Variant",
    "Cardiolipin antibody IgA",
    "Glucose for CSF",
    "Review / IHC - Histopath (upto 8 paraffin blocks and/or slides of single site)",
    "FLOW CYTOMETRY, CD 20#",
    "Cholinesterase Serum",
    "Anti Intrinsic Factor Antibody (IgG)",
    "CSF HSV II antibody IgM",
    "Onco haem: DNA only by NGS",
    "X-RAY ANKLE AP /LAT",
    "HLA A, B,C DR,DQ Matching",
    "Human Papilloma Virus (HPV) Genotyping by NGS",
    "BK Polioma Virus (Plasma) Quantitative by Real-time PCR",
    "Glucose by Glucometer",
    "Y-Chromosomal Microdeletion by PCR",
    "X-RAY ELBOW AP/LAT",
    "LCM-CDC",
    "BRCA1&2 by NGS (Germ-line)",
    "Biopsy Opinion / IHC - CoE (013AR00)",
    "Free Kappa Chain",
    "PAROXYSMAL NOCTURNAL HEMOGLOBINURIA (PNH), CONFIRMATORY TEST#",
    "Vanillylmandelic acid (VMA)",
    "Microsatellite Instability (MSI) by IHC",
    "Optima Time for Endometrial Receptivity Assay (OpERA)",
    "SS-B/La antibody",
    "Varicella Zoster antibody IgM",
    "Androstendione",
    "CSF HSV I antibody IgG",
    "Free Lambada Chain",
    "CMV (Cytomegalovirus) Qualitative By Real-time PCR",
    "Vitamin B1 (Thiamine)",
    "Double marker by Delfia Xpress",
    "Amylase,Fluid",
    "Urinary Microalbumin-24 hours",
    "Plasma glucose1 Hr (After 50G )",
    "TPMT Genotyping",
    "Factor VIII Inhibitor Study",
    "Aneuploidy detection by QF-PCR",
    "Drugs of abuse - 9 Drug panel",
    "Immunophenotyping (for Lymphoma/Leukemia), Flow cytometry#",
    "Thrombin Time",
    "Free Kappa Lambda Chain ratio-Urine ",
    "Neutrophil to Lymphocyte Ratio (NLR)",
    "Prenatal Microarray 315K",
    "Urinary Calcium spot",
    "HCV Genotyping by Sequencing",
    "Nicotine Metabolite#",
    "Urine Electrophoresis",
    "HTLV 1 and 2 antibody",
    "Urinary Nor-Metanephrine-24 hours",
    " Sanger validation, Sequencing",
    "Osmotic Fragility",
    "Protein C Antigen#",
    "Aldosterone to Renin Ratio",
    "Clostridium Difficile GDH Ag + Toxin A and B Detection From Stool",
    "Tissue Transglutaminase antibody IgG & IgA",
    "OT Microbiological Surveillance 2 Swabs",
    "Cobalt level",
    "Factor VIII Assay Activity (Photooptical Clot detection)",
    "LE Cell Phenomenon",
    "OT Microbiological Surveillance 8 Swabs",
    "# Cobalt, Random urine",
    "Aldolase",
    "Synecthan Stimulation Test(ACTH stimulation) for cortisol",
    "Immunohistochemistry, any 2 markers#",
    "METABOLIC SCREEN, COMPREHENSIVE, URINE#",
    "OT Microbiological Surveillance 9 Swabs",
    "Sirolimus Level (TDM)",
    "Prenatal Aneuploidy Test By NGS (PAN)",
    "HDV-IgM Antibody#",
    "Brucella antibody IgG",
    "Urine Electrolytes",
    "Urinary Uric acid-24 hours",
    "Hypersensitivity Pneumonitis Panel",
    "Digoxin Level (TDM)",
    "Mumps antibody IgM",
    "Urine oxalate, 24 hrs",
    "Sudan III Fat Stain,Stool",
    "Testosterone, Free/Total",
    "Allergy Food & Inhalent-ELISA",
    "Urinary Cortisol- 24 hours",
    "CYTOMEGALOVIRUS (CMV) ANTIBODIES PANEL, IgG &IgM",
    "Ganglioside Profile antibody (IgM)",
    "HIV Proviral DNA Qualitative by Real-time PCR",
    "Alcohol, Serum #",
    "Anti Islet cell Antibody",
    "Food intolerance, 217 antigen",
    "Glucose - Post Dinner",
    "Reducing substances",
    "Urinary Calcium Creatinine Ratio",
    "IMMUNOHISTOCHEMISTRY, Ki67",
    "NEWBORN SCREENING, EXTENDED",
    "Lymphoma panel (8 markers), Immunohistochemistry",
    "Desmoglein 1 and 3",
    "DLC ( DIFFERENTIAL LEUCOCYTE COUNT),FLUID",
    "Ganglioside antibody Profile (IgG)",
    "ADH - Anti Diuretic Hormone",
    "Aspergillosis antibody IgM",
    "Urinary Calcium-24 hours",
    "Echinococcus antibody IgG",
    "Everolimus (TDM)",
    "FAT GLOBULES",
    "Sm antibody",
    "Allergy-Milk f2",
    "Creatinine Clearance Test",
    "IA2-Insulin Autoantibodies#",
    "Immunohistochemistry, any 8 markers#",
    "TLC (TOTAL LEUCOCYTE COUNT),BODY FLUID",
    "Immunohistochemistry, any 5 markers#",
    "Active B-12 Level",
    "Nitroblue tetrazolium test",
    "FLUID FOR CRYSTAL",
    "Glucose,Post Prandial - 1hr (Post Lunch)",
    "Microarray Rapidsure, Deepdive (750k)",
    "Levetiracetam (TDM)",
    "Urine Chloride Spot",
    "VMA (VANILMANDELIC ACID) , RANDOM URINE#",
    "IgG Ab To E. Histolytica",
    "C.M.V. Avidity",
    "LPA (Line Probe Assay) MTB-MDR",
    "Urine citrate, 24 hrs",
    "METHYLMALONIC ACID, QUANTITATIVE, SERUM#",
    "MYASTHENIA GRAVIS PANEL#",
    "Mycoplasma Pneumoniae antibody IgM",
    "Nor-Metanephrine Level Plasma",
    "Special Stain ",
    "Allergy Food-ELISA",
    "Comprehensive Non Invasive Prenatal Testing (NIPT-COMP)",
    "Paracetamol (Acetaminophen) #",
    "Sensitivity Panel(Manual-3)",
    "Allergy Comprehensive-ELISA",
    "Diphtheria-IgG Antibody#",
    "HSV I Profile",
    "Insulin Like Growth Factor BP3 level",
    "Endomysial Antibody-IgA by IF",
    "TB Drug First Line",
    "Insulin PP (90 mts), Serum",
    "MDS Panel By FISH",
    "Parvo Virus B19 IgM",
    "Phenobarbitone (TDM)",
    "PLACENTAL GROWTH FACTOR#",
    "Antibody Against Rabies (IgG)  ",
    "Vitamin E (Tocopherol)",
    "Marijuana THC",
    "EBV (Epstein Barr Virus) Quantitative by Real-time PCR",
    "24 hours urine protein /creatinine ratio",
    "Spot Urine Urea",
    "Weil Felix",
    "Allergy-Wheat f4",
    "Histopathology - Biopsy Specimen (other than prostate & bone marrow)",
    "Autoimmune Hepatitis Profile (EIA)",
    "CLOSTRIDIUM DIFFICILE DETECTION, PCR#",
    "Molecular Karyotyping (Karyolite) POC",
    "URINE TRIGLYCERIDES (CHYLOMICRONS)",
    "Karyotyping From Blood",
    "BK Polioma virus, PCR, Qualitative",
    "C1q COMPLEMENT#",
    "ELECTROLYTES, FLUID",
    "CSF Lactate Level",
    "OPIATES SCREEN, Urine#",
    "Parvo Virus B19 IgG",
    "Vitamin A",
    "Synovial fluid analysis",
    "OncoCEPT-Liquid",
    "IHC Final diagnostic panel Histo",
    "Insulin antibody",
    "H. Pylori antibody IgG & IgA",
    "Ihc marker 1 Alk Histo",
    "JAK2 Mutation Panel (Exons 12 to 15)",
    "PORPHYRINS TOTAL, QUALITATIVE, RANDOM URINE#",
    "Scl-70 antibody",
    "Slide Review 2 (slides only)",
    "Vitamin D total - 25 hydroxy (Serum/LCMS)#",
    "PML-RARA Detection By FISH",
    "NMDA ( Cell based study )",
    "Legionella Pneumophilia Antigen From Urine",
    "Selenium level",
    "Vitamin K #",
    "# Myeloproliferative Neoplasm (MPN) reflex Panel",
    "# HLA-B5 (51/52) disease association, Whole blood, Luminex",
    "Phosphorus,  urine",
    "RUNX1-RUNX1T1 (AML1-ETO) fusion for MRD",
    "Postnatal Orion Combo",
    "Anti Phospholipid IgA#",
    "Carotid doppler",
    "Chlamydia PCR",
    "Cysticercus (T.Solium) antibody IgG",
    "HIV-2 (Human Immunodeficiency Virus-2) Quantitative by Real-time PCR",
    "OLIGOCLONAL BANDS IgG, CSF & SERUM#",
    "Urinary Uric Acid Creatinine Ratio",
    "Vitamin B2 (Riboflavin)",
    "Allergy-Aspergillus fumigatus (m3)",
    "IHC Marker PDL1 SP263 Histo",
    "Malarial Parasitic Examination",
    "ANTI DNase B#",
    "Haemoglobinuria",
    "Methotrexate Level (TDM)",
    "Fat soluble vitamins profile ",
    "Infectious Mononucleosis (Heterophile antibodies)",
    "B - Type Natriuretic Peptide",
    "Breast tumor markers, Immunohitochemistry#",
    "GILBERT SYNDROME",
    "Immunoglobulin Profile (IgG, IgM, IgA)",
    "Renin Level",
    "Urine Porphobilinogen, Qualitative",
    "COPPER, RANDOM URINE",
    "Cryptococcal Antigen",
    "Factor IX Assay (Photooptical Clot detection)",
    "GLIADIN ANTIBODY,IgA#",
    "Indian Ink Preparation",
    "TRIGLYCERIDES, FLUID#",
    "Urinary Urea-24 hours",
    "Varicella Zoster antibody IgG & IgM",
    "Methyl tetrahydro folate reductase (MTHFR) I & II muation analysis, PCR",
    "17p (p53) By FISH",
    "Deamidated Gliadin Peptide antibody IgA",
    "Adenovirus Quantitative by Real Time PCR",
    "AMINO ACIDS QUANTITATIVE, PLASMA, 45 AMINO ACIDS / FULL PANEL#",
    "Amphetamine",
    "X-RAY WRIST AP / LAT",
    "Stress Cytogenetics",
    "Human Epididymis Protein 4 (HE4)",
    "LC-1 Antibody Liver Cytosolic Antigen Type-1#",
    "Serotonin Level-Urine",
    "DHR",
    "Enhanced liver fibrosis (ELF) panel",
    "Immunofixation electrophoresis (IFE),Quantitative(with Protein electrophoresis), Serum",
    "OncoCEPT Solid (DNA)",
    "Cytology (Cytospin)",
    "Prenatal Sanger Sequencing for 2 variants ",
    "MMR IHC PANEL for MSI Histo",
    "Urinary 5-HIAA level-24 hours",
    "HIV-2 (Human Immunodeficiency Virus-2) Qualitative by Real-time PCR",
    "Mercury level",
    "TBNK (T Cell, B Cell & Natural Killer Cell)#",
    "Cocaine",
    "PHENCYCLIDINE SCREEN, Urine",
    "AG Ratio",
    "Karyotyping From Product Of Conception (POC) By NGS",
    "MLPA (Others)",
    "Bile Salt And Bile Pigment",
    "BCR-ABL Qualitative - SNG",
    "Pregnancy Test - Urine",
    "Carcinoembryonic Antigen (CEA), Body fluids",
    "Catecholamine -24 hours Urine",
    "X-RAY Skull - Lat. View",
    "CREATININE, FLUID",
    "IMMUNOGLOBULIN IgG SYNTHESIS INDEX & RATE#",
    "Immunohistochemistry, any 7 markers#",
    "IMMUNOHISTOCHEMISTRY, HER-2 / ERBB2",
    "Japanese Encephalitis Virus (JEV) Qualitative by Real-time PCR",
    "Sperm DNA Fragmentation (SCD)",
    "Cancer marker profile-Breast",
    "Propoxyphene, Urine",
    "Herpes simplex virus (HSV) type I & type II, Qualitative, PCR, CSF",
    "Lung Panel Oncocept Solid",
    "Allergy-Phadiatop Panel Naroda",
    "CLL Panel By FISH",
    "Alkaline Phosphatase Isoenzymes Electrophoresis",
    "GLIADIN ANTIBODY,IgG#",
    "HLA - T & B CELL LYMPHOCYTE CROSS MATCH#",
    "IMMUNO HISTOCHEMISTRY STUDY (Six markers)#",
    "Urinary Phosphorus- 24 hours",
    "Streptococcus pneumoniae Antigen from Urine",
    "Posaconazole  level (TDM)",
    "Urinary Magnesium-24 hours",
    "HIV-2 (Human Immunodeficiency Virus-2) Qualitative by Real-time PCR",
    "Allergy Drug-ELISA",
    "Creatinine clearance, 24 hours Urine",
    "Allergy Food & Inhalant- Microarray",
    "DNA storage for Sanger",
    "Centromere antibody",
    "COLD AGGLUTININS",
    "Microfilaria Antigen",
    "Leucocyte Alkaline Phosphatase Score",
    "Lyme disease antibody",
    "Reticulocyte production index",
    "COAGULATION PROFILE BASIC",
    "Sanger_VUS Resolution_1 Variant",
    "MLD - ORION",
    "Brucella antibody IgG & IgM",
    "IMMUNOHISTOCHEMISTRY, CD 3",
    "IMMUNOHISTOCHEMISTRY, CK 5/6",
    "LIPASE, FLUID",
    "LPA (Line Probe Assay) MTB-XDR",
    "Mycoplasma Pneumoniae antibody IgG",
    "Transferrin Saturation",
    "Microarray Low resolution Prenatal/POC CytoOne Basic ",
    "Tryptase Test",
    "ANDROGEN PROFILE",
    "Bordetella Pertussis IgG Antibody#",
    "FACTOR VII FUNCTIONAL#",
    "Factor X Assay ( Electromagnetic clot detection )",
    "Identification By Maldi TOF (Mass Spectrometry)",
    "IMMUNOHISTOCHEMISTRY, CD 4",
    "Immunohistochemistry, any 8 markers#",
    "Lamotrigine (TDM)",
    "Lp-PLA2 (LIPOPROTEI N ASSOCIATED PHOSPHOLIPASE A2), ACTIVITY#",
    "NSE",
    "NEURONAL (PARANEOPLASTIC) AUTOANTIBODIES PROFILE#",
    "ORGANIC ACIDS, QUANTITATIVE,RANDOM URINE, FULL PANEL#",
    "Estriol level",
    "Urinary Sodium-24 hours",
    "ALL Panel By FISH",
    "DMD (Duchenne Muscular Dystrophy) deletion/duplication by MLPA",
    "Imatinib Resistance Mutation Analysis",
    "Microarray Rapidsure, Constitutional (315K)",
    "TBPZA (Pyrazinamide susceptibility for MTB)",
    "Manganese level, Serum",
    "OncoCEPT Solid (Comprehensive)",
    "Allergy-Dermatophagoides farinae (d2)",
    "Allergy-Dermatophagoides pteronyssinus (d1)",
    "Allergy-Phadia NonVeg-Extensive",
    "IHC marker1 histo",
    "IHC Panel1 histo",
    "Double marker with PlGF-Delfia",
    "Borrelia burgdorferi antibody IgM (Lyme)",
    "Chlamydia Trachomatis antibody IgA",
    "Chromium level",
    "Drugs of abuse - 7 Drug panel",
    "Anti Parietal Cell Antibody ( IIF )",
    "HEPATITIS B SURFACE ANTIGEN (HBsAg) CONFIRMATION#",
    "HERPES SIMPLEX VIRUS (HSV) TYPE I, PCR, QUALITATIVE",
    "IMMUNOHISTOCHEMISTRY,p63",
    "Oxcarbazepine (TDM)",
    "Von Willebrand Factor",
    "Lymphocyte DTT treated serum cross matching",
    "Viral Encephalitis/Meningitis Panel Qualitative by Real-Time PCR",
    "BCR-ABL1 By FISH",
    "DNA Preparation",
    "Allergy-Gluten f79",
    "Allergy-House Dust Mite",
    "Allergy-Phadia Veg-Extensive",
    "HER2 neu By FISH",
    "PNH Study(IPT)(CD55 CD59 FLAER)",
    "Amyloid A#",
    "Anti Thrombin III Antigen#",
    "Voriconazole Level (TDM)",
    "CA 72-4",
    "Chloride for CSF",
    "COMPLEMENT, TOTAL (CH50)#",
    "X-RAY SKULL AP /LAT",
    "Cryptosporidium Antigen From Stool",
    "Gonococcus smear examination",
    "Chronic Leukaemia Panel (Lymphoproliferative Disorder) (IPT)",
    "Urinary Potassium-24 hours",
    "Reaction (pH)",
    "TORCH PANEL AVIDITY, IgG#",
    "# Herpes simplex virus (HSV) type I & II antibody, IgG & IgM, CSF",
    "Sperm DNA Fragmentation (SCD)",
    "HLA - T & B CELL LYMPHOCYTE CROSS MATCH#",
    "Drugs of abuse - 6 Drug panel",
    "IgLON 5",
    "Mitochondrial DNA Sequencing",
    "BCR-ABL1 Qualitative Multiplex for Detection of Transcript",
    "AFP (ALPHA FETOPROTEIN) Body Fluid",
    "ALCOHOL ETHYL GLUCURONIDE (EtG) & ETHYL SULPHATE (EtS), QUANTITATIVE ASSAY, URINE",
    "ALKAPTONURIA, URINE, QUALITATIVE#",
    "Angiotensin Converting Enzyme ,CSF#",
    "Beta Crosslaps",
    "BILIRUBIN, FLUID",
    "Brucellosis (Tube Method)",
    "Catecholamine level-Plasma",
    "COXSACKIE ANTIBODY, IgM#",
    "Factor XII Assay  ( Electromagnetic clot detection )",
    "HEMOSIDERIN, URINE",
    "HEPATITIS A& B VIRUS EVALUATION",
    "HISTOPATHOLOGY, DIRECT IMMUNOFLUORESCENCE (DIF), KIDNEY BIOPSY",
    "Jo-1 antibody",
    "Anti MAG (Myelin Associated Glycoprotein) antibody",
    "NATURAL KILLER CELLS",
    "SLE Panel - Rheumadent Clinic",
    "Rotavirus Antigen From Stool",
    "# BRAF Mutation analysis",
    "NMO-MOG Antibody ( Cell based study )",
    "# Toxoplasma antibody, IgM, CSF",
    "Immunohistochemistry, p16INK4a",
    "Pre/Post Natal Diagnosis Chromosome 13, 18, 21, X & Y By FISH",
    "TBDrug5",
    "Chikungunya IgG-Rapid",
    "ORION_TRIO PROBAND",
    "Allergy-Phadia veg panel Mini",
    "TBDrug19",
    "Allergy Inhalants-ELISA",
    "Bone Marrow Biopsy",
    "Minor BCR-ABL1 Quantitative RQPCR p190",
    "IgVH Mutation analysis for CLL",
    "Prenatal Orion Combo",
    "Acid Phosphatase Total",
    "Aluminum level",
    "Arsenic Level",
    "BACTERIAL MENINGITIS SCREEN#",
    "New Born Screening-Biotinidase",
    "Hemochromatosis (HFE gene) Mutation Analysis (2 common mutations) by Sanger Sequencing",
    "IMMUNOGLOBULIN IgD & IgE TYPING, SERUM#",
    "IMMUNOHISTOCHEMISTRY, S100",
    "MTHFR gene analysis- 2 exons (5 & 8)#",
    "MUCOPOLYSACCHARIDOSIS (MPS) SCREEN, URINE#",
    "PORPHYRINS TOTAL, QUANTITATIVE, 24- HOUR URINE#",
    "REDUCING SUBSTANCES,Urine",
    "SOLUBLE TRANSFERIN RECEPTOR#",
    "Tetanus Toxoid-IgG Antibody#",
    "TOXOPLASMA DNA DETECTION , PCR#",
    "Varicella Zoster Virus IgG antibody,CSF#",
    "Bicarbonate, Urine",
    "11 deoxy cortisol",
    "COMPREHENSIVE LYMPHOCYTES SUBSET ANALYSIS BY FLOW CYTOMETRY ",
    "Baby First™,TMS for amino acids, organis acids,fatty acid oxidation disorders",
    "Covid IgG ELISA",
    "Barbiturate Screen, Qualitative, Urine",
    "# Panel Reactive Antigen (PRA), HLA Class I & Class II",
    "# Porphobilinogen (PBG), Quantitative, 24 hours urine",
    "ColoComprehensive ",
    "Platelet Count, Plasma",
    "NTM / MOTT Drug susceptibility testing by MIC",
    "ORION PLUS (Whole Exome plus Mitochondrial DNA Sequencing)",
    "Allergy-Banana f92",
    "Allergy-Egg White f1",
    "IHC ER, PR, Her2Neu with Ki67 Histo",
    "Tacrolimus Mutation Study For CYP3A4",
    "PGT-A FOR 5 EMBRYOS (Extended)",
    "BCL2/IGH FISH on FFPE block",
    "BCL6 FISH on FFPE Block",
    "HRR Gene Panel ",
    "PGT-A FOR 6 EMBRYOS (Extended)",
    "PGT-A FOR 3 EMBRYOS (Extended)",
    "KRAS+NRAS+BRAF Oncocept Solid",
    "HBA1/HBA2 gene deletion/duplication study by MLPA for Alpha-Thalassemia",
    "Panel Reactive Antibody HLA-Class I",
    "Panel Reactive Antibody HLA-Class II",
    "Congenital Adrenal Hyperplasia (CAH) Combo (Seq+MLPA)",
    "Acetylcholinesterase, Blood #",
    "ALKAPTONURIA, URINE, QUANTITATIVE#",
    "ALLERGY DUST PANEL#",
    "B - 2 Microglobulin-Urine",
    "Borrelia burgdorferi antibody IgG (Lyme)",
    "COXSACKIE ANTIBODY, IgG#",
    "PIVKA level",
    "Drug Test,General Toxicology,Blood#",
    "EGFR by NGS",
    "ENA Screen#",
    "Factor V Leiden Activity Test",
    "Hepcidin #",
    "IMMUNOHISTOCHEMISTRY, VIMENTIN",
    "IMMUNOHISTOCHEMISTRY, DESMIN",
    "LEISHMANIA (KALA AZAR) ANTIBODY IgG#",
    "Leptin level",
    "Leptospira,Blood by DFM",
    "LEPTOSPIROSIS(URINE)#",
    "METHYLMALONIC ACID, QUALITATIVE, URINE#",
    "Monospot test for infectiousMononucleosis#",
    "Total P1 NP",
    "Serum Albumin Ascitis Gradient",
    "STRIATED / SKELETAL MUSCLE ANTIBODY, IFA#",
    "WILSON DISEASE (ATP7B GENE) MUTATION ANALYSIS BY NEXT GENERATION SEQUENCING#",
    "CSF TPHA",
    "Aspergilosis Serology IgG and IgM",
    "# Epidermal (pemphigus) antibody",
    "BRCA1&2 MLPA",
    "Beta Thalassemia gene Mutation Detection, PCR  ",
    "Urea / Creatinine Ratio",
    "Androgen Receptor (AR) by IHC",
    "Onco haem: RNA only by NGS",
    "ORION_TRIOS_RELATIVE-1",
    "ORION_TRIOS_RELATIVE-2",
    "IHC, ER-PR & Her2Neu",
    "Somatic BRCA 1&2 ",
    "Allergy-Eggyolk f75",
    "Allergy-Blomia tropicalis (d201)",
    "Allergy-Phadia Rhinitis Panel",
    "Allergy-Phadia NonVeg Mini",
    "Allergy-Phadia Eczema Panel",
    "Allergic Bronchopulmonary Aspergillosis Panel",
    "MYC By FISH",
    "BP180 and BP230",
    "KIR Typing",
    "IHC, Her2neu Histo",
    "Blocks for review  6- 10 (Block and Slides)",
    "ORION -Single gene (Single gene NGS)",
    "Sanger_VUS Resolution_2 variants",
    "GeneXpert-Flu",
    "Oncocoept Liquid Comprehensive",
    "CBFB-MYH11 (INV16) fusion for MRD",
    "1IHC",
    "Aldosterone/Plasma Renin Activity(PRA) Ratio#",
    "Bone specific alkaline phosphatase",
    "AMINO ACID, NON- KETOTIC HYPERGLYCINEMIA PANEL QUANTITATIVE, CSF & PLASMA#",
    "AMINO ACIDS, QUANTITATIVE URINE, 45 AMINO ACIDS/ FULL PANEL#",
    "ARYLSULFATASE A#",
    "Bioavailable Testosterone",
    "Karyotyping From Amniotic Fluid",
    "DPT Antibodies, Serum #",
    "FLOW CYTOMETRY, CD 34#",
    "GALACTOSE -1-PHOSPHATE,QUANTITATIVE, BLOOD#",
    "HAMS TEST (Acidified serum lysis)#",
    "HEINZ BODIES, PERIPHERALBLOOD#",
    "Histamine, Plasma#",
    "IMMUNOHISTOCHEMISTRY, CD 20",
    "IMMUNOHISTOCHEMISTRY, EPITHELIAL MEMBRANE ANTIGEN (EMA)",
    "JC (John Cunningham ) Virus Polioma Quantitative by Real-time PCR",
    "Legionella Pneumophila IgG antibodies#",
    "Legionella Pneumophila IgM antibodies#",
    "LEUKEMIA DIAGNOSTIC PANEL: CLL/HCL/SLL (BASIC)#",
    "Liquid Biospy for Lung Cancer by NGS#",
    "METHYLMALONIC ACID, QUANTITATIVE, URINE#",
    "TBDrug18",
    "Amylase,Urine",
    "Plasma Glucose 30 mts",
    "Immunohistochemistry, CD45 (LCA)#",
    "5 Fluorouracil (5FU) Assay (DPYD)",
    "PML-RARA Fusion Gene Detection (Quantitative)",
    "CD18 [ For screening Leucocyte adhesion deficiency ], Flowcytometry",
    "# Carnitine, Serum",
    "# Creatine Phosphokinase (CPK) Isoenzyme electrophoresis",
    "# Epidermal (pemphigus) antibody, (in dilutions)",
    "# Hepatitis D virus (HDV) antibody, IgM",
    "# Hyperornithinemia-Hyperammonemia-Homocitrullinuria (HEE) syndrome ",
    "# Neutrophil gelatinase associated lipocalin (NGAL), Urine",
    "Succinylacetone Urine",
    "Syphilis panel",
    "Febrile agglutinins panel (combined brucella, widal & weil felix)",
    "Immunohistochemistry, ALK D5F3 (Lung carcinoma)",
    "Myelodysplastic syndromes cytogentics panel (Karyotyping and FISH)",
    "Biofire Pneumonia Plus Panel",
    "HLA-B*57:01 for Abacavir Sensitivity",
    "Microsatellite Instability (MSI) by IHC",
    "Review / IHC - Histopath (46 to 50 paraffin blocks and/or slides of single site)",
    "Quadruple Marker - Delfia",
    "HBV Genotyping",
    "CMV (Cytomegalovirus) Quantitative BY Real-time PCR",
    "Allergy- Almond f20",
    "Allergy-Chicken f83",
    "Allergy-Codfish f3",
    "Allergy-Garlic f47",
    "Allergy-Orange f33",
    "Allergy-Peanut f13",
    "Allergy-Soybean f14",
    "Allergy-Yeast f45",
    "Allergy-Phadia Inhalent Panel",
    "Allergy-Phadia Non-Veg Seafood",
    "Screening Test For Toxic Usage of Drug",
    "MGMT METHYLATION ASSAY",
    "Paraneoplastic Panel (6 Ag)",
    "TBDrug3",
    "PGT-A FOR 7 EMBRYOS (Extended)",
    "PGT-A FOR 2 EMBRYOS (Extended)",
    "Lumos Focus (Female)",
    "Lumos Focus (Male)",
    "EGFR BY REAL TIME PCR",
    "CSF Measles IgG Index",
    "X & Y Chromosome By FISH",
    "Modified ZN Stain",
    "Hereditary Cancer Gene Panel - ORION FOCUS",
    "Microsatellite Instability",
    "Oncocept TMB",
    "PIVKA level",
    "Microarray High resolution Postnatal CytoOne Advanced",
    "Anti A Antibody Titre",
    "Non-Tuberculous Mycobacterium Qualitative by Real Time PCR",
    "Itraconazole Level (TDM)",
    "Myotonic Dystrophy Type I & Type II",
    "Fungus susceptibility testing by MIC",
    "Non-invasive PGT-A (1 EMBRYO) ",
    "NBS-TMS",
    "Orion- Express (WES-Whole Exome Sequencing)",
    "17 – KETOSTEROIDS, 24–HOUR URINE#",
    "ACTH stimulation for 17OHP",
    "5-HIAA (5- HYDROXY INDOLE ACETIC ACID), RANDOM URINE#",
    "Allergy-Phadia Rhinitis Panel",
    "Allergy-Phadia Eczema Panel",
    "Allergy-Basic food panel (7 parameters)",
    "Allergy-Phadiatop, Inf",
    "Allergy, ACTH#",
    "Allergy, Ampicillin#",
    "Allergy-Beef f27",
    "Allergy-Chicken f83",
    "ALLERGY, CRAB#",
    "Allergy-Dermatophagoides farinae (d2)",
    "Allergy-Egg White f1",
    "Allergy-Gluten f79",
    "Allergy, Ibuprofen#",
    "Allergy-Mugwart w6",
    "ALLERGY, MUTTON(Meat)#",
    "Allergy, Penicilloyl G#",
    "Penicillin V ( c2)",
    "Allergy-Phadiatop, Adult",
    "Allergy, Rifampicin#",
    "ALLERGY, SHRIMP(Prawn / Jhinga)#",
    "Amoxycillin (c204)",
    "Allergy,Ciprofloxacin#",
    "Allergy,Diclofenac#",
    "Insulinhuman (c73)",
    "Allergy,Paracetamol#",
    "Allergy-Penicillium chrysogenum m1",
    "Allergy,Sulpha#",
    "AMINO ACIDS QUALITATIVE #",
    "Anaerobic Culture",
    "Beta Trace Protein level",
    "Cancer marker profile-Breast",
    "BREAST CANCER PANEL 2#",
    "CA 27.29 &CA 15.3 BREAST CANCER MARKERS PANEL",
    "Cardiolipin antibody IgG & IgM",
    "CYP2C19 Genotyping for Clopidogrel Resistance Assay",
    "COXSACKIE ANTIBODIES, IgG & IgM PANEL#",
    "CHEST PA VIEW",
    "cell block preperation",
    "Dengue Qualitative by Real-time PCR",
    "ORION -Single gene (Single gene NGS)",
    "Cardiac Echo",
    "EGFR (EXON 18, 19, 20, 21)  By Sequencing",
    "Factor XIII screen",
    "FERTILITY HARMONE PROFILE",
    "HER2 neu By FISH",
    "Prader-Willi/ Angelman Syndromes By FISH",
    "FOETAL / PERINATAL BIOPSY",
    "KOH Preparation",
    "HIV Drug Resistance and Genotyping (PI, NRTI, NNRTI)",
    "HLA A,B & DR By Luminex",
    "Huntington Disease Molecular Assay",
    "CD-3 CD-4 CD-8 Lymphocyte Count ( IPT )",
    "Breast tumor markers, Immunohitochemistry#",
    "INFERTILITY PANEL, MALES",
    "LIPASE IN URINE#",
    "Heavy Metal Analysis from blood",
    "Heavy Metal Analysis from blood - 2",
    "Myoglobin level",
    "Neuro Angio Profile",
    "Nor-Adrenaline (Nor-epinephrine), Plasma#",
    "NPM1 GENE MUTATION#",
    "POTASSIUM, FLUID",
    "Rubella Avidity",
    "U1-SnRNP antibody",
    "Vancomycin level",
    "Vasculitis Profile",
    "VGKC ( Cell based study )",
    "Treponena Pallidum Total antibody",
    "Allergy-Phadia Veg-Extensive",
    "Allergy-Phadia NonVeg-Extensive",
    "Arthritis Profile-1",
    "CSF Routine",
    "VISIT 200",
    "Novel Corona Virus (COVID-19)",
    "Benzodiazepam",
    "Lymphocyte Auto Patients cross matching",
    "1p-19q co-deletion by FISH",
    "Dengue antibody IgM",
    "Dengue Antigen NS1 Elisa",
    "Dengue antibody IgG",
    "VISIT 50",
    "HB Electrophoresis ( Capillary )",
    "EPSTEIN - BARR VIRUS ANTIBODY (EBV) (IgG & IgM)",
    "Myeloma profile II",
    "Baby First™, Elementary (NBS Basic 5)",
    "Baby First™, Elementary (NBS Basic 7)",
    "Baby First™, Enhanced (NBS extended-Basic 7 + TMS)",
    "Beta 2 Glycoprotein 1 antibody (IgG+IgM)",
    "Ihc marker 1 IDH1 Histo",
    "Visit Charges(Covid)",
    "Dengue Antigen (NS1)- Rapid",
    "Cotinine level",
    "Torch Complex (8 parameters)",
    "Quadruple Marker",
    "Growth hormone stimulation test",
    "IRON PROFILE WITH STFR",
    "Cyclosporine Level (TDM)",
    "ORION -Single gene (Single gene NGS)",
    "ORION (WES-Whole Exome Sequencing)",
    "G6PD Quantitative",
    "CLL Panel By FISH",
    "IgG level",
    "Factor II (Prothrombin) G20210A by Real-time PCR",
    "COVID19 Qualitative by Real time PCR",
    "Antibodies to SARS-CoV-2 (Total)",
    "Covid 19 - Antibody Panel",
    "Oncocept combined panel (DNA & RNA)",
    "COVID-19 RAPID TEST",
    "SARS CoV2 IgG antibody (ELISA)",
    "CSF IgG Index",
    "HBB Gene Mutational Analysis for Beta Thalassemia(All Exons of HBB)",
    "Myeloma Profile 3",
    "Hepatitis B surface antigen (HbsAg)",
    "Allergy-Milk f2",
    "Microdeletion Non Invasive Prenatal Testing (NIPT-MD)",
    "OncoCEPT Solid (Comprehensive)",
    "Microsatellite Instability",
    "SMA (Spinal Muscular Atrophy) deletion/duplication study by MLPA",
    "Biofire Meningitis panel",
    "Covid IgG CLIA",
    "BT CT",
    "USG OBSTETRIC SCAN/ANOMALY",
    "USG EARLY PREGNANCY",
    "USG OBESTETRIC SCAN WITH DOPPLER",
    "USG ABDOMEN & PELVIS",
    "USG EARLY PREGNANCY WITH TVS",
    "USG ABDOMEN & KUB",
    "USG Breast",
    "USG PELVIS WITH TVS",
    "USG Neck",
    "USG OBSTETRIC SCAN WITH BPP",
    "USG VENOUS DOPPLER UL/LL SINGLE",
    "USG ARTERIAL DOPPLER SINGLE",
    "USG GUIDED FNAC",
    "USG ABDOMEN PELVIS &TVS",
    "USG NT NB",
    "USG SCROTUM DOPPLER",
    "USG FOLLICULAR STUDY / TVS",
    "USG Fetal Echo",
    "VISIT 250",
    "Anti Phospholipid Antibody",
    "USG FOLLICULAR REVIEW",
    "Myeloperoxidase (MPO) stain, Blood/Bone marrow",
    "Anti Myeloperoxidase antibody (ANCA-MPO)",
    "IgG4Subclass",
    "COVID19 Qualitative by Real time PCR",
    "Karyotyping cytogenetic study for oncology",
    "USG Thyroid",
    "Creatinine, 12 hours Urine",
    "Ceruloplasmin level",
    "FSH and LH stimulation by Gonadotropin releasing hormone (GnRH)",
    "Endomysial Antibody-IgG by IF",
    "# Epstein-Barr virus (EBV) antibody to nuclear antigen (NA), IgM",
    "EBV EA antibody IgG",
    "HLA - DQ for Celiac disease",
    "Methadone",
    "DGP And TTG Screening Test",
    "VZV (Varicella-Zoster Virus) Qualitative by Real-time PCR",
    "MLPA (Others)",
    "Hereditary Cancer Gene Panel - ORION FOCUS",
    "HLA Extended Typing (A,B,C,DRB1,DQB1,DRB3,DRB4,DRB5 AND DQA1) High Resolution ",
    " Sanger validation, Sequencing",
    "Zinc Transporter 8 (ZnT8) Antibody",
    "Adenosine Deaminase From Body Fluids",
    "Steroid Hormonal Panel",
    "Bone marrow second opinion (stained slides)",
    "Deamidated Gliadin Peptide antibody IgG",
    "Immunohistochemistry, BCL-2",
    "Immunohistochemistry, Synaptophysin",
    "Immunohistochemistry,, HEPPAR-1",
    "Metanephrines, Fractionated, Random urine",
    "Stone Analysis ( FT-IR )",
    "Food allergy panel (Qualitative)",
    "HBA1/HBA2 gene deletion/duplication study by MLPA for Alpha-Thalassemia",
    "Double Negative T-cells (DNT), Flowcytometry",
    "Immunohistochemistry, CD10",
    "Immunohistochemistry, CD117 (CK-KIT)",
    "Immunohistochemistry, Chromogranin A",
    "Her2-neu by IHC",
    "Renal Function Test",
    "Karyotyping From Blood",
    "HISTOPATHOLOGY, DIRECT IMMUNOFLUORESCENCE (DIF), KIDNEY BIOPSY",
    "Covid Spike Protein IgG",
    "Dengue Rapid(NS1+Antibody)",
    "Semen Analysis With Morphology",
    "VisitCharges75",
    "Aneuploidy detection by QF-PCR",
    "Lumos Comprehensive (Female)",
    "Lumos Comprehensive (Male)",
    "Pregnancy Associated Plasma Protein - A",
    "Prader-Willi/ Angelman Syndromes by MS-MLPA",
    "SCA (Spinocerebellar Ataxia) Panel (SCA1, SCA2, SCA3, SCA6, SCA7, SCA10, SCA12)+DRPLA",
    "MLL By FISH",
    "HBV Drug Resistance and Genotyping",
    "CSF-Viral Panel Qualitative by Real-time PCR",
    "HLA DQA1",
    "G6PD Qualitative",
    "GeneXpert-TB CB-NAAT",
    "Liquid Base Cytology PAP",
    "High Vaginal Swab NB",
    "Troponin I",
    "EBV EBNA antibody IgG",
    "FNAC reporting ( up to 4 smears)",
    "Tacrolimus Level (TDM)",
    "Semen Fructose",
    "CULTURED AFB ANTITUBERCULAR DST, 5 DRUGS PANEL#",
    "Biopsy Small 3",
    "Chylomicron",
    "Autoimmune Hepatitis Panel-MP",
    "Bactec Aerobic Culture",
    "Tryptase Test",
    "HLA TYPING HIGH RESOLUTION ( HLA - A B C DRB1 DQB1)",
    "Immunophenotyping for Acute Leukemia with reflex conventional karyotyping",
    "ALL CYTOGENETIC PANEL",
    "RHEUMATOID FACTOR IgM CLASS",
    "OncoCEPT CGP (Comprehensive Genomic Profile)- 590 gene",
  ];

  List<dynamic> selectedtest = [];
  var selectedtestvalue = ''.obs;

  String validateInputs() {
    final RegExp nameRegExp = RegExp(r'[a-zA-Z\s]+');
    final RegExp phoneRegExp = RegExp(
        r'^(?:(?:\+|0{0,2})91(\s*[\ -]\s*)?|[0]?)?[7896]\d{9}|(\d[ -]?){10}\d$'); //(r'[0-9]');
    final RegExp emailRegExp = RegExp(
        r'^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$'); //(r'^[a-zA-Z0-9_@.-]+');
    // Validation for each field
    print(selectedTests);

    if (username.text.isEmpty &&
        emailCntrl.text.isEmpty &&
        mobnoCtrl.text.isEmpty &&
        selectedtest.isEmpty) {
      return 'Please fill the details';
    }
    if (selectedtest.isEmpty) {
      return "Please select at least one test.";
    }
    if (username.text.isEmpty || !nameRegExp.hasMatch(username.text)) {
      return 'Please enter a valid name';
    }

    if (emailCntrl.text.isEmpty || !emailRegExp.hasMatch(emailCntrl.text)) {
      return 'Please enter vaild e-mail';
    }
    if (mobnoCtrl.text.isEmpty || !phoneRegExp.hasMatch(mobnoCtrl.text)) {
      return 'Please enter a valid 10-digit phone number';
    }

    return "";
  }

  Future sendUserEmail(
      {required List<dynamic> selectedTests,
      required String email,
      required String name,
      required String mobno}) async {
    print("selectedList ${selectedTests.join(', ')}");
    print(email);
    const serviceId = 'service_r3ybd0s';
    const templateId = 'template_vow75of';
    const userId = 'u4CcmrAA8dSNowyBW';
    final url = Uri.parse('https://api.emailjs.com/api/v1.0/email/send');
    // Define the table structure HTML
    const tableHtml = '''
    <table style="width:100% ;border:1px solid black;">
      <tr>
        <th style="border:1px solid black;" >Test Name</th>
        <th style="border:1px solid black;" >Total Cost</th>
        <th style="border:1px solid black;" >Discount</th>
      </tr>
  ''';

    final rowsHtml = selectedTests.map((test) => '''
      <tr>
        <td style="border:1px solid black;">$test</td>
        <td style="border:1px solid black;">1000</td>
        <td style="border:1px solid black;">10%</td>
      </tr>
  ''').join();

    const tableCloseHtml = '</table>';

    final fullHtml = '$tableHtml$rowsHtml$tableCloseHtml';

    print(fullHtml);
    final response = await http.post(
      url,
      headers: {'Content-Type': 'application/json'},
      body: json.encode({
        'service_id': serviceId,
        'template_id': templateId,
        'user_id': userId,
        'template_params': {
          'from_name': 'GHS CARE PLUS',
          'sendername': name,
          'senderemail': email,
          'sendermobilno': mobno,
          'tablerows': fullHtml,
        },
      }),
    );
    print(response.body);
    if (response.statusCode == 200) {
      print("Mail Success");
      return true;
    } else {
      return false;
    }
  }

  Future sendAdminEmail(
      {required List<dynamic> selectedTests,
      required String email,
      required String name,
      required String phoneNumber}) async {
    print("selectedList ${selectedTests.join(', ')}");
    print(email);
    const serviceId = 'service_r3ybd0s';
    const templateId = 'template_jmgn5pd';
    const userId = 'u4CcmrAA8dSNowyBW';
    final url = Uri.parse('https://api.emailjs.com/api/v1.0/email/send'); /* */
    final response = await http.post(
      url,
      headers: {'Content-Type': 'application/json'},
      body: json.encode({
        'service_id': serviceId,
        'template_id': templateId,
        'user_id': userId,
        'template_params': {
          'from_name': name,
          'sendername': name,
          'sendermobno': phoneNumber,
          'senderemailid': email,
          'selectedtest': selectedTests.join(', '),
        },
      }),
    );
    print(response.body);
    if (response.statusCode == 200) {
      print("Mail Success");
      return true;
    } else {
      return false;
    }
  }
}

/*  String? isValidName(String name) {
      // Regular expression pattern for name validation
      final nameRegex = RegExp(r'^[a-zA-Z]+(?:\s+[a-zA-Z]+)*$');
      return nameRegex.hasMatch(name) ? null : 'Invalid Name.';
    }

    /*   String? isValidEmail(String email) {
      // Regular expression pattern for email validation
      final emailRegex = RegExp(r'^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$');
      return emailRegex.hasMatch(email) ? null : 'Invalid E-mail Id.';
    }

    String? isValidMobileNo(String mobileNo) {
      // Regular expression pattern for email validation
      final mobilenoregex = RegExp(r'[0-9]');
      return mobilenoregex.hasMatch(mobileNo) ? null : 'Invalid Mobile Number';
    } */

    String? nameError = isValidName(username.text);
    //String? emailError = isValidEmail(emailCntrl.text);
    //String? mobileNumError = isValidEmail(mobnoCtrl.text);

    // Display error message for checkbox
    /* if (!areAllChecked) {
      return 'Please select at least one test.';
    } */

    // Display error message for name
    if (nameError != null) {
      return 'Please enter a valid name.';
    }
    // Display error message for email
    /* if (emailError != null) {
      return 'Please enter a valid email-id.';
    } */

    /*  if (mobileNumError != null) {
      return 'Please enter a valid Mobile Number.';
    }
 */
    return ''; // if all are valid
 */